In [1]:
import tensorflow
from tensorflow.keras.preprocessing.text import one_hot


c:\Users\shree\anaconda3\envs\genai\Lib\site-packages\keras\src\export\tf2onnx_lib.py:8: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(np, "object"):


In [2]:
## Sentences

sent = [
    'I love my dog',
    'I love my cat',
    'I am a good boy',
    'I am a good developer',
    'I love to code',
    'I love to eat biryani',
]

In [3]:
sent

['I love my dog',
 'I love my cat',
 'I am a good boy',
 'I am a good developer',
 'I love to code',
 'I love to eat biryani']

In [4]:
## Define the vocabulary size
vocab_size = 10000

In [5]:
## One-hot representation the sentences
one_hot_sentences = [one_hot(words, vocab_size) for words in sent]
one_hot_sentences


[[1188, 8445, 219, 9991],
 [1188, 8445, 219, 5248],
 [1188, 199, 3166, 4909, 5902],
 [1188, 199, 3166, 4909, 6488],
 [1188, 8445, 5523, 2689],
 [1188, 8445, 5523, 7320, 1916]]

In [6]:
## Word embedding representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [8]:
sent_length = 8
embedded_docs = pad_sequences(sequences = one_hot_sentences , padding = 'pre', maxlen = sent_length)  
# post padding for adding zeros at end, making the length same

In [9]:
embedded_docs

array([[   0,    0,    0,    0, 1188, 8445,  219, 9991],
       [   0,    0,    0,    0, 1188, 8445,  219, 5248],
       [   0,    0,    0, 1188,  199, 3166, 4909, 5902],
       [   0,    0,    0, 1188,  199, 3166, 4909, 6488],
       [   0,    0,    0,    0, 1188, 8445, 5523, 2689],
       [   0,    0,    0, 1188, 8445, 5523, 7320, 1916]], dtype=int32)

In [10]:
## feature reqpresentation
dim = 10

In [11]:
model = Sequential()
model.add(Embedding(input_dim = vocab_size, output_dim = dim))
model.compile('adam', 'mse')


In [12]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [13]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step


array([[[-0.04465955,  0.04844612,  0.01253709, -0.040416  ,
          0.03712133,  0.01460146,  0.02324491,  0.03394899,
          0.02030507, -0.04553822],
        [-0.04465955,  0.04844612,  0.01253709, -0.040416  ,
          0.03712133,  0.01460146,  0.02324491,  0.03394899,
          0.02030507, -0.04553822],
        [-0.04465955,  0.04844612,  0.01253709, -0.040416  ,
          0.03712133,  0.01460146,  0.02324491,  0.03394899,
          0.02030507, -0.04553822],
        [-0.04465955,  0.04844612,  0.01253709, -0.040416  ,
          0.03712133,  0.01460146,  0.02324491,  0.03394899,
          0.02030507, -0.04553822],
        [-0.01432621, -0.00590918,  0.01060004,  0.03914735,
          0.03013137, -0.01505611,  0.00148097, -0.01821259,
          0.0089576 , -0.01425141],
        [-0.02680945,  0.01796423,  0.03203119, -0.02267728,
          0.00032464,  0.0207588 ,  0.02426757, -0.03038228,
         -0.02346883, -0.0112405 ],
        [-0.04127539, -0.02083174,  0.04288005,  0.0

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 1188, 8445,  219, 9991], dtype=int32)

In [16]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step


array([[[-0.04465955,  0.04844612,  0.01253709, -0.040416  ,
          0.03712133,  0.01460146,  0.02324491,  0.03394899,
          0.02030507, -0.04553822],
        [-0.04465955,  0.04844612,  0.01253709, -0.040416  ,
          0.03712133,  0.01460146,  0.02324491,  0.03394899,
          0.02030507, -0.04553822],
        [-0.04465955,  0.04844612,  0.01253709, -0.040416  ,
          0.03712133,  0.01460146,  0.02324491,  0.03394899,
          0.02030507, -0.04553822],
        [-0.04465955,  0.04844612,  0.01253709, -0.040416  ,
          0.03712133,  0.01460146,  0.02324491,  0.03394899,
          0.02030507, -0.04553822],
        [-0.01432621, -0.00590918,  0.01060004,  0.03914735,
          0.03013137, -0.01505611,  0.00148097, -0.01821259,
          0.0089576 , -0.01425141],
        [-0.02680945,  0.01796423,  0.03203119, -0.02267728,
          0.00032464,  0.0207588 ,  0.02426757, -0.03038228,
         -0.02346883, -0.0112405 ],
        [-0.04127539, -0.02083174,  0.04288005,  0.0