## Bag of words implementation

In [1]:
import pandas as pd


In [2]:
spam_msgs = pd.read_csv('spam.csv', encoding='latin-1', usecols=['v1', 'v2'])

In [3]:
spam_msgs.head()
## changing the name of the columns
spam_msgs.columns = ['label', 'message']

In [4]:
spam_msgs

label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [5]:
## Data cleaning and preprocessing
import re
import nltk
nltk.download('stopwords')


[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\shree\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [6]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [7]:
corpus = []
for i in range(0, len(spam_msgs)):
    review = re.sub('[^a-zA-Z]',' ',spam_msgs['message'][i])
    review = review.lower()
    review = review.split()
    # print(review)
    review = [ps.stem(word) for word in review if not word in set(stopwords.words('english'))]
    review = ' '.join(review)
    # print(review)
    corpus.append(review)

In [8]:
corpus

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri wkli comp win fa cup final tkt st may text fa receiv entri question std txt rate c appli',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though',
 'freemsg hey darl week word back like fun still tb ok xxx std chg send rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'winner valu network custom select receivea prize reward claim call claim code kl valid hour',
 'mobil month u r entitl updat latest colour mobil camera free call mobil updat co free',
 'gonna home soon want talk stuff anymor tonight k cri enough today',
 'six chanc win cash pound txt csh send cost p day day tsandc appli repli hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw',
 'search right word thank breather

In [9]:
### Creating the Bag of Words model

from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(max_features=2500, binary=True) ## For binart BOW , we use binary=True

In [10]:
X = cv.fit_transform(corpus).toarray()

In [11]:
print(X)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [12]:
cv.vocabulary_

{'go': np.int64(870),
 'point': np.int64(1579),
 'crazi': np.int64(479),
 'avail': np.int64(147),
 'bugi': np.int64(310),
 'great': np.int64(904),
 'world': np.int64(2433),
 'la': np.int64(1164),
 'cine': np.int64(401),
 'got': np.int64(889),
 'wat': np.int64(2366),
 'ok': np.int64(1476),
 'lar': np.int64(1172),
 'joke': np.int64(1128),
 'wif': np.int64(2401),
 'oni': np.int64(1484),
 'free': np.int64(803),
 'entri': np.int64(675),
 'wkli': np.int64(2422),
 'comp': np.int64(435),
 'win': np.int64(2405),
 'fa': np.int64(716),
 'cup': np.int64(493),
 'final': np.int64(760),
 'tkt': np.int64(2214),
 'st': np.int64(2001),
 'may': np.int64(1311),
 'text': np.int64(2156),
 'receiv': np.int64(1686),
 'question': np.int64(1649),
 'std': np.int64(2017),
 'txt': np.int64(2271),
 'rate': np.int64(1667),
 'appli': np.int64(103),
 'dun': np.int64(617),
 'say': np.int64(1776),
 'earli': np.int64(623),
 'hor': np.int64(1011),
 'alreadi': np.int64(71),
 'nah': np.int64(1413),
 'think': np.int64(2178),

# N-grams

In [21]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(max_features=500, binary=True, ngram_range=(2,2))
X = cv.fit_transform(corpus).toarray()

In [22]:
cv.vocabulary_

{'free entri': np.int64(127),
 'rate appli': np.int64(328),
 'per request': np.int64(300),
 'claim call': np.int64(54),
 'call claim': np.int64(24),
 'claim code': np.int64(55),
 'entitl updat': np.int64(113),
 'updat latest': np.int64(431),
 'latest colour': np.int64(211),
 'free call': np.int64(125),
 'call mobil': np.int64(32),
 'mobil updat': np.int64(261),
 'chanc win': np.int64(53),
 'win cash': np.int64(474),
 'repli hl': np.int64(336),
 'hl info': np.int64(185),
 'txt word': np.int64(426),
 'dont miss': np.int64(102),
 'let know': np.int64(218),
 'feel like': np.int64(118),
 'yeah got': np.int64(497),
 'tell anyth': np.int64(394),
 'mobil charg': np.int64(256),
 'repli ye': np.int64(338),
 'go home': np.int64(148),
 'anyth lor': np.int64(3),
 'call repli': np.int64(36),
 'nokia mobil': np.int64(280),
 'mobil free': np.int64(258),
 'free camcord': np.int64(126),
 'pleas call': np.int64(310),
 'deliveri tomorrow': np.int64(96),
 'lt gt': np.int64(234),
 'miss call': np.int64(253)